<?php
$produtos = array(
    1 => array('nome' => 'ROCK','preco'=>'10000','descricao'=>'Apenas a vista','imagem'=>'./content/guaxiniim.jpg'),
    2 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    3 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    4 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    5 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    6 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    7 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    8 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    9 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    10 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    11 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    12 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    13 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    14 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    15 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    16 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    17 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    18 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    19 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    20 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    21 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    22 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    23 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    24 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    25 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    26 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    27 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    28 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    29 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>''),
    30 => array('nome' => '','preco'=>'','descricao'=>'','imagem'=>'')
);
?>